name: Build LaTeX document
# Trigger the workflow on push or pull request
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      FINAL_FILENAME: Dewit_03281500_Yakoub_13861700_2020.pdf
      LATEX_FILENAME: main.pdf
      MAIN_LATEX: main.tex
      DATE_TIMEZONE: Europe/Brussels
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set timezone for date
        run: |
          sudo timedatectl set-timezone ${{ env.DATE_TIMEZONE }}
      - name: Get current date
        run: echo "::set-env name=CURRENT_DATETIME::$(date +'%d/%m/%Y %H:%M:%S')"
      - name: Generate version number
        run: echo "::set-env name=CURRENT_VERSION::$(date +'%d%m%Y_%H-%M-%S')"
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.MAIN_LATEX }}
      - name: rename ${{ env.LATEX_FILENAME }} to ${{ env.FINAL_FILENAME }}
        run: |
          mv "${{ env.LATEX_FILENAME }}" "${{ env.FINAL_FILENAME }}"
      - name: Upload result file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FINAL_FILENAME }}
          path: ${{ env.FINAL_FILENAME }}
      - name: Upload result file into releases
        if: github.ref == 'refs/heads/master'
        uses: Xotl/cool-github-releases@v1.1.2
        with:
          mode: update
          tag_name: ${{ env.CURRENT_VERSION }}
          release_name: PDF - ${{ env.CURRENT_DATETIME }}
          replace_assets: true
          assets: ${{ env.FINAL_FILENAME }}
          initial_mrkdwn: Release auto-generated by Github Actions 🎉
          github_token: ${{ github.token }}
