name: Build LaTeX document
# Trigger the workflow on push or pull request
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
      - name: Upload result file
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: main.pdf
